/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ExtensionsExtensionIdImport } from './routes/extensions/$extensionId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExtensionsExtensionIdRoute = ExtensionsExtensionIdImport.update({
  id: '/extensions/$extensionId',
  path: '/extensions/$extensionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/extensions/$extensionId': {
      id: '/extensions/$extensionId'
      path: '/extensions/$extensionId'
      fullPath: '/extensions/$extensionId'
      preLoaderRoute: typeof ExtensionsExtensionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/extensions/$extensionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/extensions/$extensionId'
  id: '__root__' | '/' | '/extensions/$extensionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionsExtensionIdRoute: typeof ExtensionsExtensionIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionsExtensionIdRoute: ExtensionsExtensionIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/extensions/$extensionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/extensions/$extensionId": {
      "filePath": "extensions/$extensionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
